from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist" / "newz.lua"

SOURCE_ORDER = (
    "Main",
    "Config",
    "Profiler",
    "Bounds",
    "Visuals",
    "Scheduler",
    "PlayerESP",
    "CorpseESP",
    "Freecam",
    "ESP",
    "UI",
    "NeverLose",
)

SOURCES = {
    "Main": ROOT / "src" / "Main.lua",
    "Config": ROOT / "src" / "Config.lua",
    "Profiler": ROOT / "src" / "Core" / "Profiler.lua",
    "Bounds": ROOT / "src" / "Core" / "Bounds.lua",
    "Visuals": ROOT / "src" / "Core" / "Visuals.lua",
    "Scheduler": ROOT / "src" / "Core" / "Scheduler.lua",
    "PlayerESP": ROOT / "src" / "Modules" / "PlayerESP.lua",
    "CorpseESP": ROOT / "src" / "Modules" / "CorpseESP.lua",
    "Freecam": ROOT / "src" / "Modules" / "Freecam.lua",
    "ESP": ROOT / "src" / "Modules" / "ESP.lua",
    "UI": ROOT / "src" / "Ui.lua",
    "NeverLose": ROOT / "vendor" / "NeverLose.lua",
}


def read_sources() -> dict[str, str]:
    result: dict[str, str] = {}

    for name in SOURCE_ORDER:
        path = SOURCES[name]

        if not path.is_file():
            raise FileNotFoundError(
                f"Missing build input: {path}"
            )

        text = path.read_text(
            encoding="utf-8"
        )

        if not text.strip():
            raise RuntimeError(
                f"Build input is empty: {path}"
            )

        result[name] = text

    return result


def fingerprint(
    sources: dict[str, str]
) -> str:
    digest = hashlib.sha256()

    for name in sorted(sources):
        digest.update(
            name.encode("utf-8")
        )
        digest.update(b"\0")
        digest.update(
            sources[name].encode("utf-8")
        )
        digest.update(b"\0")

    return digest.hexdigest()


def xor_hex_encrypt(
    plaintext: str,
    key: str
) -> str:
    data = plaintext.encode("utf-8")
    key_bytes = key.encode("utf-8")

    encrypted = bytes(
        b ^ key_bytes[i % len(key_bytes)]
        for i, b in enumerate(data)
    )

    return encrypted.hex()


def build_bundle(
    sources: dict[str, str]
) -> str:
    fp = fingerprint(sources)
    key = fp[:32]

    entries = []

    for name in SOURCE_ORDER:
        encrypted_hex = xor_hex_encrypt(
            sources[name],
            key
        )

        entries.append(
            f'    {name} = "{encrypted_hex}",'
        )

    joined_entries = "\n".join(entries)

    return f'''-- Generated by scripts/build.py
-- Build fingerprint: {fp}
-- Do not edit this file manually.

local Environment =
    (getgenv and getgenv())
    or _G

local Sources = {{
{joined_entries}
}}

local Key = "{key}"

local BXor =
    bit32
    and bit32.bxor

assert(
    type(BXor) == "function",
    "Newz bundle requires bit32.bxor"
)

local function Decode(HexStr)
    local Output =
        table.create(
            math.floor(
                #HexStr / 2
            )
        )

    local KeyLength =
        #Key

    local KeyIndex =
        1

    local OutputIndex =
        1

    for I = 1, #HexStr, 2 do
        local ByteValue =
            tonumber(
                HexStr:sub(
                    I,
                    I + 1
                ),
                16
            )

        assert(
            ByteValue ~= nil,
            "Invalid hexadecimal bundle data"
        )

        local KeyByte =
            string.byte(
                Key,
                KeyIndex
            )

        Output[OutputIndex] =
            string.char(
                BXor(
                    ByteValue,
                    KeyByte
                )
            )

        OutputIndex += 1

        KeyIndex =
            (KeyIndex % KeyLength)
            + 1
    end

    return table.concat(
        Output
    )
end

local function Traceback(Error)
    if
        debug
        and type(debug.traceback)
            == "function"
    then
        return debug.traceback(
            tostring(Error),
            2
        )
    end

    return tostring(Error)
end

local function Execute(Name)
    local Encoded =
        Sources[Name]

    assert(
        type(Encoded) == "string",
        "Missing bundle source: "
        .. tostring(Name)
    )

    local Source =
        Decode(
            Encoded
        )

    local Chunk,
        LoadError =
            loadstring(
                Source,
                "@newz/bundle/"
                .. Name
            )

    assert(
        Chunk,
        "Falha ao carregar bundle "
        .. Name
        .. ": "
        .. tostring(LoadError)
    )

    local Success,
        Result =
            xpcall(
                Chunk,
                Traceback
            )

    assert(
        Success,
        "Erro executando bundle "
        .. Name
        .. ": "
        .. tostring(Result)
    )

    return Result
end

local PreviousBundle =
    Environment.NEWZ_BUNDLE

local Config =
    Execute("Config")

local ProfilerModule =
    Execute("Profiler")

local BoundsModule =
    Execute("Bounds")

local VisualsModule =
    Execute("Visuals")

local SchedulerModule =
    Execute("Scheduler")

local PlayerESPModule =
    Execute("PlayerESP")

local CorpseESPModule =
    Execute("CorpseESP")

local FreecamModule =
    Execute("Freecam")

local ESPModule =
    Execute("ESP")

local UIModule =
    Execute("UI")

local NeverLose =
    Execute("NeverLose")

Environment.NEWZ_BUNDLE = {{
    Config = Config,

    ProfilerModule = ProfilerModule,
    BoundsModule = BoundsModule,
    VisualsModule = VisualsModule,
    SchedulerModule = SchedulerModule,

    PlayerESPModule = PlayerESPModule,
    CorpseESPModule = CorpseESPModule,
    FreecamModule = FreecamModule,
    ESPModule = ESPModule,

    UIModule = UIModule,
    NeverLose = NeverLose,
}}

local Success,
    Result =
        xpcall(function()
            return Execute(
                "Main"
            )
        end, Traceback)

Environment.NEWZ_BUNDLE =
    PreviousBundle

if not Success then
    error(
        Result,
        0
    )
end

return Result
'''


def main() -> None:
    sources = read_sources()

    bundle = build_bundle(
        sources
    )

    DIST.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    DIST.write_text(
        bundle,
        encoding="utf-8",
        newline="\n",
    )

    print(
        f"Built {DIST.relative_to(ROOT)}"
    )

    print(
        f"Fingerprint: {fingerprint(sources)}"
    )

    print(
        f"Size: {DIST.stat().st_size:,} bytes"
    )


if __name__ == "__main__":
    main()
